### ISSUE TITLE
support specifying id field

### ISSUE THREAD

**Issue by haoliangyu** [haoliangyu/koop-provider-csv#2]

**Comment by hhkaos** [comment]
Hi @haoliangyu, I have been playing around with your code today and did some changes to make it work with a CSV file I have produced using [csv-writer](https://www.npmjs.com/package/csv-writer). I have also improved the code to avoid the warning about the idField.

I can do a [pull request of my code](https://github.com/haoliangyu/koop-provider-csv/compare/master...esri-es:master) if you want.

By the way, thanks for sharing :smile:

**Comment by haoliangyu** [comment]
@hhkaos This is an awesome job. I especially like the stream approach to handle CSV file :+1: Please do the PR!

Can you add a reference/link to the idField documentation? I am not clear about the logic.

**Comment by hhkaos** [comment]
Sure!, I had this same issue [some time ago with another provider](https://github.com/koopjs/koop-provider-google-sheets/issues/11).

You can find the [documentation here](https://koopjs.github.io/docs/usage/provider#setting-provider-metadata-in-getdata):

[<img width="885" alt="Screen Shot 2019-04-24 at 16 48 03" src="https://user-images.githubusercontent.com/826965/56669066-ded09680-66b0-11e9-846d-3f850d0d1b06.png">](https://koopjs.github.io/docs/usage/provider#setting-provider-metadata-in-getdata)

I have done another improvement based on an issue I was having with a 13MB CSV full of tweets ^_^
